
model:
  backbone: 'vgg'
  amp: False
  cuda: True

attack:
  adv_type: 'mtd'
  atk_iters: 20
  step_size: 8

data:
  dataset: 'VOC'
  dataset_root: '../datas/VOCdevkit/'
  data_use: 'clean[2007]+clean[2012]'
  num_workers: 8

train:
  basenet: 'vgg16_reducedfc.pth'
  batch_size: 32
  resume: null
  start_iter: 0
  multi_gpu: False
  lr: 0.001
  max_iter: 120000
  momentum: 0.9
  weight_decay: 0.0005
  gamma: 0.1
  focal: False
  clean_mix: True
  save_folder: 'weights/'
  log_folder: 'logs/'

test:
  trained_model: ''
  save_folder: 'eval/'
  confidence_threshold: 0.01
  top_k: 5
  robust: False
  con_weights: [1.,1.]
  save_tp_fp: None
  log_folder: 'logs/'